### ISSUE TITLE
Concurrency in Dispatch

### ISSUE THREAD

**Issue by zebulonj** [staltz/callbag-subject#2]
Yo Staltz...

Take a peek at this: https://github.com/zebulonj/callbag-behavior-subject/commit/c0d73f578a6163cb973bd27add11a579be186833

I encountered a race condition (or concurrency issue) of sorts in an application of my`BehaviorSubject`. In short, if a sink receives data (`type === 1`) that it synchronously acts on causing itself or any other sink observing the `Subject` to terminate (`type === 2`), you end up with an index-out-of-range error (the `.splice(...)` mutates the `sinks` array while it is still being iterated over based on its initial length).

Same issue could arise in your `Subject`, so I'm calling it to your attention here.

**Comment by staltz** [comment]
Well noted, thanks!
