### ISSUE TITLE
Cannot complete

### ISSUE THREAD

**Issue by miraklez** [staltz/callbag-subject#5]
Trying to solve this problem : 
Try to create an EventBus using callbag but cannot stop it when sending 2.

```javascript
const makeSubject = require('callbag-subject')
const subscribe = require('callbag-subscribe')
const { pipe } = require('callbag-basics')

const EventBus = makeSubject()

const observer = {
  next: data => console.log( `DATA: ${data}` ),
  error: err => console.error( `ERROR: ${err}` ),
  complete: () => console.log( 'Done!' )
}

pipe(
  EventBus,
  subscribe( observer )
)

setInterval(() => { EventBus(1, 'some data')}, 1000)
setTimeout(() => { EventBus(2) }, 5000)
```

Console display : 
```bash
DATA: some data
DATA: some data
DATA: some data
DATA: some data
DATA: some data
Done!
DATA: some data
DATA: some data
DATA: some data
DATA: some data
DATA: some data
DATA: some data
...
```

[Try online](https://stackblitz.com/edit/js-26ejca)

**Comment by zebulonj** [comment]
@miraklez My understanding of the callbags spec, reflected in the way that `callbag-subject` and `callbag-subscribe` are implemented, is that a `type == 2` from upstream (the source) does not _trigger_ completion so much as it should _reflect_ completion. If it is coming from the source, it should mean that the source doesn't intend to send any additional messages.

In contrast, when the **sink** sends a `type == 2` to its source, the source must honor that and stop sending data to _that sink_. You'll find that `callbag-subject` does that, disconnecting the sink that sends the `type == 2` message.

Your example would look like this:
```
const makeSubject = require('callbag-subject')
const subscribe = require('callbag-subscribe')
const { pipe } = require('callbag-basics')

const EventBus = makeSubject()

const observer = {
  next: data => console.log( `DATA: ${data}` ),
  error: err => console.error( `ERROR: ${err}` ),
  complete: () => console.log( 'Done!' )
}

pipe(
  EventBus,
  subscribe( observer )
)

const interval = setInterval(() => { EventBus(1, 'some data')}, 1000);

setTimeout(() => {
  clearInterval(interval);
  EventBus(2);
}, 5000)
```

**Comment by staltz** [comment]
This is an interesting issue, because I do see the point of the example seeming to be broken, but the contract that this library gives is "*A callbag listener sink which is also a listenable source*", and your example code that calls `EventBus` is operating on it as a listener sink, so it's the example code's responsibility to correctly use it as a sink.

Also note that the Callbag spec says "*A callbag MUST NOT be delivered data after it has been terminated*", so this means that it's the code that controls the callbag which has the responsibility of not breaking the spec, in other words, your example code that calls `EventBus(1,d)` or `EventBus(2)` has to abide by the spec.

That said, I think there is space for another library that has "safer" guarantees so that even if you use the library in the wrong way, it will still try to figure out what's the best spec-compliant behavior afterwards.

**Comment by miraklez** [comment]
First of all, thinks you @zebulonj and @staltz for taking valuable time for the community.

> so it's the example code's responsibility to correctly use it as a sink.

I think that's the tricky part, hard to find some valuable exemple when a callbag act as as source AND a sink at the same time (what i need, in this implementation).
Maybe the trick will be using the **talkback** function ? need to investigate a little bit more and play with it.
The callbag spec seems simple in a first point of vue but **inter-communication** between source and sink are hard to understand (in my beginer point of vue, a way too abstract but this is what you call @staltz callback hell becoming callback heaven :)), specialy when you need to complete (stop) a specific sink from a source.

>  it's the code that controls the callbag which has the responsibility of not breaking the spec, in other words, your example code that calls EventBus(1,d) or EventBus(2) has to abide by the spec.

Thank you for pointing this, i will investigate in that way.

> That said, I think there is space for another library that has "safer" guarantees so that even if you use the library in the wrong way, it will still try to figure out what's the best spec-compliant behavior afterwards.

What about externalising each piece of the specific part responsible of **inter-communication** between sink and source ?

**Comment by loreanvictor** [comment]
Well according to the README:
> Use this like you would use RxJS Subject.

So maybe it should also [behave like RxJS Subject](https://stackblitz.com/edit/rxjs-jlzi8h?devtoolsheight=60), and kind of _die_ when it receives a completion signal? i.e. something like this:

```js

function makeSubject() {
  let sinks = [];
  let done = false;
  return (type, data) => {
    if (done) return;
    if (type === 0) {
      const sink = data;
      sinks.push(sink);
      sink(0, t => {
        if (t === 2) {
          const i = sinks.indexOf(sink);
          if (i > -1) sinks.splice(i, 1);
        }
      });
    } else {
      const zinkz = sinks.slice(0);
      for (let i = 0, n = zinkz.length, sink; i < n; i++) {
        sink = zinkz[i];
        if (sinks.indexOf(sink) > -1) sink(type, data);
      }
      if (type === 2) {
        done = true;
        sinks.length = 0;
      }
    }
  }
}

module.exports = makeSubject;
```

**Comment by staltz** [comment]
Yeah, I'd gladly merge a PR for adding a simple `done` flag @loreanvictor.

**Comment by loreanvictor** [comment]
@staltz sure thing. I also made sure that a subject cannot accept new sinks after completion (this is not part of the spec, but matches RxJS subject's behavior).
